>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry
>>> bg = BaseGeometry()
>>> bg.area()
Traceback (most recent call last):
...
Exception: area() is not implemented
>>> bg = BaseGeometry()
>>> bg.integer_validator("checkme", 0)
Traceback (most recent call last):
...
ValueError: checkme must be greater than 0
>>> bg = BaseGeometry()
>>> bg.integer_validator("checkme", -999)
Traceback (most recent call last):
...
ValueError: checkme must be greater than 0
>>> bg = BaseGeometry()
>>> bg.integer_validator("tufo_pro_max", 69)
>>> bg = BaseGeometry()
>>> bg.integer_validator("tufo", None)
Traceback (most recent call last):
...
TypeError: tufo must be an integer
>>> bg = BaseGeometry()
>>> bg.integer_validator("tufo", "hello!")
Traceback (most recent call last):
...
TypeError: tufo must be an integer
>>> bg = BaseGeometry()
>>> bg.integer_validator("tufo", "50")
Traceback (most recent call last):
...
TypeError: tufo must be an integer
>>> bg = BaseGeometry()
>>> bg.integer_validator("tufo", {"flaged": 2})
Traceback (most recent call last):
...
TypeError: tufo must be an integer
>>> bg = BaseGeometry()
>>> bg.integer_validator("tufo", {"flaged": 2, "Served": 0})
Traceback (most recent call last):
...
TypeError: tufo must be an integer
>>> bg = BaseGeometry()
>>> bg.integer_validator("tufo", [1, 2, 3])
Traceback (most recent call last):
...
TypeError: tufo must be an integer
>>> bg = BaseGeometry()
>>> bg.integer_validator("tufo", (1, 2, 3))
Traceback (most recent call last):
...
TypeError: tufo must be an integer
>>> bg = BaseGeometry()
>>> bg.integer_validator("tufo", {6, 9})
Traceback (most recent call last):
...
TypeError: tufo must be an integer
>>> bg = BaseGeometry()
>>> bg.integer_validator("tufo", True)
Traceback (most recent call last):
...
TypeError: tufo must be an integer
>>> bg = BaseGeometry()
>>> bg.integer_validator()
Traceback (most recent call last):
...
TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'
>>> bg = BaseGeometry()
>>> bg.integer_validator("age_of_ice")
Traceback (most recent call last):
...
TypeError: integer_validator() missing 1 required positional argument: 'value'
